version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: sso
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin12345
    expose:
      - "5432"
    ports:
        - "5432:5432"

  redis:
    image: redis:5.0.6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data