server:
  error:
    include-message: always
    include-binding-errors: always
app:
  server: "http://localhost:8080/"

email:
  sender: your-email@example.com


spring:
  datasource:
    username: admin
    password: admin12345
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    ssl:
      enabled: false
      algorithm: TLSv1.2
  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    username: your email
    password: api
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587
